vo=gpu-next
hwdec=mediacodec
hwdec-software-fallback=no
android-dovi-overlay=yes
demuxer-dovi-split=no
sid=1
sub-font-size=27
vd-lavc-o=dovi_surface_decoder=1,dovi_p7_surface_probe=1,dovi_diagnostics=1
msg-level=all=trace
